###  
GET https://jsonplaceholder.typicode.com/comments

accept: application/json  
foo: bar

postId = 5
# id=21

### 

@hostname = httpbin.org

GET https://{{hostname}}/get

accept: application/json  

